# Generated by Django 3.0.6 on 2023-03-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_buscar_reportes_camaras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReporte', models.DateField()),
                ('planta', models.IntegerField()),
            ],
        ),
    ]
