# Generated by Django 3.0.6 on 2023-03-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empaque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_buscar_reportes_camaras',
            name='planta',
            field=models.CharField(max_length=25),
        ),
    ]
