# Generated by Django 3.0.6 on 2023-03-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empaque', '0002_auto_20230303_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_buscar_reportes_camaras',
            name='hora',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
