# Generated by Django 3.0.6 on 2023-01-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_buscar_legajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('departamento', models.CharField(max_length=25)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='model_buscar_legajo_exportar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('departamento', models.CharField(max_length=25)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('export', models.CharField(max_length=25)),
            ],
        ),
    ]
