# Generated by Django 3.0.6 on 2023-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZTime', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model_buscar_legajo_exportar',
        ),
        migrations.AddField(
            model_name='model_buscar_legajo',
            name='export',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
