# Generated by Django 3.0.6 on 2023-01-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZTime', '0002_auto_20230130_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_exportar_legajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajoExport', models.IntegerField()),
                ('departamentoExport', models.CharField(max_length=25)),
                ('desdeExport', models.DateField()),
                ('hastaExport', models.DateField()),
                ('exportExport', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='model_buscar_legajo',
            name='export',
        ),
    ]
