# Generated by Django 3.0.6 on 2023-01-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZTime', '0003_auto_20230130_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_exportar_legajo',
            old_name='departamentoExport',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='model_exportar_legajo',
            old_name='desdeExport',
            new_name='desde',
        ),
        migrations.RenameField(
            model_name='model_exportar_legajo',
            old_name='exportExport',
            new_name='export',
        ),
        migrations.RenameField(
            model_name='model_exportar_legajo',
            old_name='hastaExport',
            new_name='hasta',
        ),
        migrations.RenameField(
            model_name='model_exportar_legajo',
            old_name='legajoExport',
            new_name='legajo',
        ),
    ]
