# Generated by Django 3.0.6 on 2023-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZTime', '0004_auto_20230130_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_proceso_fichadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('departamento', models.CharField(max_length=25)),
            ],
        ),
    ]
